### PR TITLE
Medmij-1 sample data added

### PR DESCRIPTION
**Pull request by JakeThom**
Folders and files are kebabbed. Ids and "createddate" updated.

### CODE REVIEW

**Review by lejlabecirspahic — COMMENTED** [review]
I believe it's not correct to use `medmij-1` for servicetype reference as it will not be resolved on sample data connector, given that service name is `medmij`.
cc @ndzlatar

**Comment by JakeThom** [comment]
Oh of course. Should I combine Medmij - 1 and Medmij - 2 into one Medmij folder then?

**Comment by lejlabecirspahic** [comment]
> Oh of course. Should I combine Medmij - 1 and Medmij - 2 into one Medmij folder then?

atm we don't have a support for a multiple datasets for the same source, so yes - it would make sense to combine files and put them under default account.

**Review by lejlabecirspahic — CHANGES_REQUESTED** [review]
Please rename the following:
1. medication-v2 -> medication-v-2
2. practitioner-v2 -> practitioner-v-2

You can leave a single file for patient and practitioner.

Given we've combined MedMij responses from different patients into a single dataset, does it make sense to change `subject` in files so it looks like data belongs to the same patient? ie
```
"subject": {
            "display": "ELLEN XXX_BALTUS",
            "reference": "Patient/61bef2d5-86f2-49bb-b475-e5e1db1a92f2"
        }
   
```

**Pull request merged**
